apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  labels:
    app: openldap
    app.kubernetes.io/component: openldap
    app.kubernetes.io/instance: openldap
  name: openldap
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: openldap
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: openldap
    spec:
      containers:
      - args:
        - --copy-service
        image: docker.io/osixia/openldap:1.5.0
        imagePullPolicy: IfNotPresent
        name: openldap
        ports:
        - containerPort: 389
          protocol: TCP
        - containerPort: 636
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext:
          capabilities:
            drop:
            - MKNOD
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
