---

application_name: backend-oidc
application_template: app.yml

service_image: quay.io/redhat_naps_da/backend-oidc
service_image_tag: 0.0.2

application_properties: application.properties
application_configmap: "{{ application_name }}"
application_configmap_key: "{{ application_properties }}"

binary_imagestream_template: binary-imagestream.yml
