---

- set_fact:
    namespace: "{{ project_name }}"
    resources_dir: "{{ resources_base_dir }}/frontend"
    work_dir_name: frontend
- include_role:
    name: ../roles/frontend
  when: >
    ACTION is not defined or
    ACTION is none or
    ACTION|trim() == "" or
    ACTION|trim() == "install"


- include_role:
    name: ../roles/frontend
    tasks_from: uninstall
  when: >
    ACTION is defined and
    ACTION|trim() == "uninstall"
